revert to Matlab

diff --git a/extr/petster/matlab b/extr/petster/matlab
--- a/extr/petster/matlab
+++ b/extr/petster/matlab
@@ -1,7 +1,8 @@
 #! /bin/sh
 #
 # Execute a Matlab script.  This is a wrapper around Matlab that makes
-# it easier to run Matlab in batch mode and log the output of scripts. 
+# it easier to run Matlab in batch mode and log the output of scripts.
+# Used with Matlab 2009B.  
 #
 # PARAMETERS
 # 	$1	    	The Matlab program (with or without .m; may contain directory) 
@@ -13,10 +14,20 @@
 #			logfile name, such that multiple instances can
 #			run in parallel. 
 # 
-# Example:  to run m/map.m, use ./matlab m/map 
+# FILES
+#	error.log	Errors from all runs of this script are logged
+#			in this file  
+#
+# EXAMPLE
+#
+#	to run m/map.m, use ./matlab m/map.m 
 #
 # Matlab scripts run using this method usually don't use command line
-# arguments. Instead, environment variables are passed.  
+# arguments.  Instead, environment variables are passed.  
+#
+# If multiple runs are done in parallel with the same network/type
+# arguments, their logfiles may overwrite each other.  In that case,
+# users must set a different $TMPDIR. 
 #
 
 #
@@ -36,10 +47,10 @@ exec 6>>error.log
 # The command to use
 MATLAB=matlab
 
-# The options to use
+# The options to use for Matlab 
 MATLAB_OPTIONS="-nodesktop -nosplash"
 if [ -z "$jvm_enable" ] ; then
-  MATLAB_OPTIONS="$MATLAB_OPTIONS -nojvm"
+	MATLAB_OPTIONS="$MATLAB_OPTIONS -nojvm"
 fi
 
 # Prefix
@@ -48,50 +59,50 @@ export PREFIX
 
 # The name of script within Matlab
 SCRIPT="$1"
-export MATLAB_NAME="$(basename $SCRIPT | sed -re 's,\.m$,,')"
+export MATLAB_NAME="$(basename $SCRIPT | sed -E -e 's,\.m$,,')"
 echo >&4 "MATLAB_NAME=«$MATLAB_NAME»"
 
 # Check that the file exists
 FILENAME="$SCRIPT"
 if echo "$FILENAME" | grep -qvE '\.m$' ; then
-    FILENAME="$FILENAME.m"
-    if ! [ -r "$FILENAME" ] ; then
-	echo >&2 "*** No such file:  $FILENAME"
-	exit 1
-    fi
+	FILENAME="$FILENAME.m"
+	if ! [ -r "$FILENAME" ] ; then
+		echo >&2 "*** No such file:  $FILENAME"
+		exit 1
+	fi
 fi
 
 #
 # Logging
 #
 
-LOGNAME=$USER.$MATLAB_NAME
+LOGNAME="$MATLAB_NAME"
 # This is a list of variable we want to be used in the log filename to
 # make it unique.
-[ "$TYPE"    ]     	&& LOGNAME=$LOGNAME.$TYPE
-[ "$NAME"   ]      	&& LOGNAME=$LOGNAME.$NAME
-[ "$DECOMPOSITION" ]	&& LOGNAME=$LOGNAME.$DECOMPOSITION
-[ "$STATISTIC" ]	&& LOGNAME=$LOGNAME.$STATISTIC
-[ "$METHOD" ]		&& LOGNAME=$LOGNAME.$METHOD 
-[ "$KIND"   ]      	&& LOGNAME=$LOGNAME.$KIND
-[ "$CLASS"   ]      	&& LOGNAME=$LOGNAME.$CLASS
-[ "$NETWORK" ]		&& LOGNAME=$LOGNAME."`basename "$NETWORK"`"
-[ "$SPECIES"   ]      	&& LOGNAME=$LOGNAME.$SPECIES
+[ "$type"    ]     	&& LOGNAME="$LOGNAME"."$type"
+[ "$name"   ]      	&& LOGNAME="$LOGNAME"."$name"
+[ "$decomposition" ]	&& LOGNAME="$LOGNAME"."$decomposition"
+[ "$statistic" ]	&& LOGNAME="$LOGNAME"."$statistic"
+[ "$method" ]		&& LOGNAME="$LOGNAME"."$method"
+[ "$kind"   ]      	&& LOGNAME="$LOGNAME"."$kind"
+[ "$class"   ]      	&& LOGNAME="$LOGNAME"."$class"
+[ "$group"   ]      	&& LOGNAME="$LOGNAME"."$group"
+[ "$year"   ]      	&& LOGNAME="$LOGNAME"."$year"
+[ "$network" ]		&& LOGNAME="$LOGNAME"."`basename "$network"`"
 
 for PARAM in $MATLAB_PARAMS
 do
-    eval [ "\$$PARAM"   ]   	&& eval LOGNAME=\$LOGNAME.\$$PARAM
+	eval [ "\$$PARAM"   ]   	&& eval LOGNAME=\$LOGNAME.\$$PARAM
 done
 
-echo >&4 "LOGNAME=«$LOGNAME»"
+echo >&4 "LOGNAME='$LOGNAME'"
 
 export LOGNAME
 
-export TMP_BASE=${TMP-/tmp}/`basename $0`.$LOGNAME$PREFIX
-echo >&2 "   $TMP_BASE.log"
-echo >&4 "TMP_BASE=«$TMP_BASE»"
+export TMP_BASE="${TMPDIR-/tmp}"/m."$LOGNAME$PREFIX"
+export LOGFILE="$TMP_BASE".log
+printf >&2 '\t%s\n' "$LOGFILE"
 
-export LOGFILE=$TMP_BASE.log
 
 #
 # Other configurations
@@ -103,38 +114,50 @@ DISPLAY=
 # will send them to stderr.  (Matlab has been known to trigger such errors.)  
 export LIBC_FATAL_STDERR_=1
 
-DIR_SCRIPT="$(dirname $SCRIPT)"
+DIR_SCRIPT="$(dirname "$SCRIPT")"
 if echo "$DIR_SCRIPT" | grep -vq '^/' ; then
-    DIR_SCRIPT="$PWD/$DIR_SCRIPT"
+	DIR_SCRIPT="$PWD/$DIR_SCRIPT"
 fi
 export MATLABPATH="$DIR_SCRIPT:$MATLABPATH"
 echo >&4 MATLABPATH=«$MATLABPATH»
 
-$MATLAB -logfile $LOGFILE -r "$MATLAB_NAME" $MATLAB_OPTIONS  \
-     >$TMP_BASE.out 2>&1 <<EOF  ||
+# We have to use <<EOF or else Matlab will read its standard input and hang.
+"$MATLAB" -logfile "$LOGFILE" -r "$MATLAB_NAME" $MATLAB_OPTIONS  \
+	>"$TMP_BASE".out 2>&1 <<EOF  ||
 EOF
 { 
-    echo >&2 "*** error in $TMP_BASE.log"; 
-    echo >&6 "*** error in $TMP_BASE.log"
-    exit 1; 
+	# Note: Matlab normally always exists with exit code 0 on a
+	# syntax or other "normal" error, so if we are here Matlab
+	# probably crashed or was killed by a signal. 
+
+	exitstatus="$?"
+	echo >&2 "*** error in $TMP_BASE.log"
+	echo >&6 "*** error in $TMP_BASE.log"
+	if [ "$exitstatus" = 0 ] ; then
+		echo >&2 "*** error:  exit status of Matlab was 0"
+		exit 1
+	fi
+	exit "$exitstatus"
 }
 
-# We have to use <<EOF or else Matlab will read its standard input and hang.
 
 # Matlab does not exit(!=0) on error but prints ???. 
-grep -E '(\?\?\?|^\*\*\* )' $TMP_BASE.log && 
+grep -qE '(\?\?\?|^\*\*\* )' $TMP_BASE.log && 
 {
-    echo "*** error in $TMP_BASE.log"
-    echo >&6 "*** error in $TMP_BASE.log"
-    <$TMP_BASE.log sed -re '
-/^(\?\?\?|\*\*\*)/h
-/^Error in ==> /!d
-s,^Error in ==> ([^ ]+) at ([0-9]+)$,\1.m:\2:,
-n
-	' >&2
-    exit 1
+	echo "*** error in $TMP_BASE.log"
+	echo >&6 "*** error in $TMP_BASE.log"
+	<$TMP_BASE.log >&2 sed -E -e '
+		# Matlab output actually contains { and } sequences. 
+		s,.,,g
+		/\?\?\?|\*\*\*|[Ee]rror/!d
+		s,^(|\?\?\? )Error (in|using) ==> ([^ ]+) at ([0-9]+)$,\3.m:\4: ,
+		T
+		N
+		s,\n,,
+	'
+	exit 1
 }
 
-echo >>$TMP_BASE.log '=== FINISHED ==='
+echo >>"$TMP_BASE".log '=== FINISHED SUCCESSFULLY ==='
 
 exit 0
